# Generated by Django 4.0.6 on 2022-08-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=25)),
                ('lname', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=60)),
                ('city', models.CharField(max_length=50)),
                ('adderss', models.CharField(max_length=80)),
                ('Imag_profile', models.ImageField(upload_to='')),
                ('Discription', models.TextField()),
                ('instagram', models.CharField(max_length=60)),
                ('whatsapp', models.CharField(max_length=60)),
                ('github', models.CharField(max_length=60)),
                ('linkdin', models.CharField(max_length=60)),
            ],
        ),
    ]
