# Generated by Django 4.0.6 on 2022-08-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutMe_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='Phon',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
