# Generated by Django 4.0.6 on 2022-08-15 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AboutMe_app', '0003_contact_my'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='Discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='linkdin',
            new_name='linkedin',
        ),
    ]
