# Generated by Django 4.0.6 on 2022-08-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutMe_app', '0004_rename_discription_information_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cv_my',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('body', models.TextField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
