# Generated by Django 4.0.6 on 2022-08-17 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AboutMe_app', '0005_cv_my'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv_my',
            name='time',
        ),
    ]
