# Generated by Django 4.0.6 on 2022-09-03 10:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cateqory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_my',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cv_my',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('body', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=25)),
                ('lname', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=60)),
                ('city', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('Phon', models.CharField(max_length=20)),
                ('adderss', models.CharField(max_length=80)),
                ('Imag_profile', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('instagram', models.CharField(max_length=60)),
                ('whatsapp', models.CharField(max_length=60)),
                ('github', models.CharField(max_length=60)),
                ('linkedin', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('created', models.DateField(default=datetime.datetime(2022, 9, 3, 10, 52, 39, 194718, tzinfo=utc))),
                ('image', models.ImageField(upload_to='image/article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cateqory', models.ManyToManyField(to='home.cateqory')),
            ],
        ),
    ]
