# Generated by Django 4.0.6 on 2022-09-03 11:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_body_article_body_1_article_body_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tip',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 9, 3, 11, 21, 2, 655098, tzinfo=utc)),
        ),
    ]
