# Generated by Django 4.0.6 on 2022-09-03 13:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_article_views_coment_views_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 9, 3, 13, 41, 39, 957982, tzinfo=utc)),
        ),
    ]
