# Generated by Django 4.0.6 on 2022-09-03 13:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_article_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coment',
            name='views',
        ),
        migrations.AddField(
            model_name='coment',
            name='nomber_massage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 9, 3, 13, 50, 31, 728235, tzinfo=utc)),
        ),
    ]
