# Generated by Django 4.0.6 on 2022-09-03 14:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_article_body_4_article_title_1_article_title_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_body_1',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='image_body_2',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='image_body_3',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='image_body_4',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 9, 3, 14, 25, 19, 756011, tzinfo=utc)),
        ),
    ]
