# Generated by Django 4.0.6 on 2022-09-05 12:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_article_created_alter_article_image_body_4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 9, 5, 12, 26, 52, 81499, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article/imag'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_body_1',
            field=models.ImageField(blank=True, null=True, upload_to='article/imag'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_body_2',
            field=models.ImageField(blank=True, null=True, upload_to='article/imag'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_body_3',
            field=models.ImageField(blank=True, null=True, upload_to='article/imag'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_body_4',
            field=models.ImageField(blank=True, null=True, upload_to='article/imag'),
        ),
    ]
