# Generated by Django 4.0.6 on 2022-09-05 12:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_article_created_alter_article_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 9, 5, 12, 34, 46, 249350, tzinfo=utc)),
        ),
    ]
