# Generated by Django 4.0.6 on 2022-09-08 19:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_article_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body_5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='body_6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='body_7',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='image_body_5',
            field=models.ImageField(blank=True, null=True, upload_to='article/imag'),
        ),
        migrations.AddField(
            model_name='article',
            name='image_body_6',
            field=models.ImageField(blank=True, null=True, upload_to='article/imag'),
        ),
        migrations.AddField(
            model_name='article',
            name='image_body_7',
            field=models.ImageField(blank=True, null=True, upload_to='article/imag'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_5',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='title_6',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='title_7',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='body_4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 9, 8, 19, 46, 16, 864731, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_4',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
