# Generated by Django 4.0.6 on 2022-09-08 20:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_article_body_2_remove_article_image_body_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body_2',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='image_body_2',
            field=models.ImageField(blank=True, null=True, upload_to='article/imag'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_2',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 9, 8, 20, 10, 46, 606749, tzinfo=utc)),
        ),
    ]
