# Generated by Django 4.0.6 on 2022-09-09 10:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_article_body_2_article_image_body_2_article_title_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='body_8',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='image_body_8',
            new_name='image_body_10',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='title_8',
            new_name='title_10',
        ),
        migrations.AddField(
            model_name='article',
            name='body_10',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='body_11',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='body_12',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='body_13',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='body_14',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='body_9',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='image_body_11',
            field=models.ImageField(blank=True, null=True, upload_to='article/imag'),
        ),
        migrations.AddField(
            model_name='article',
            name='image_body_12',
            field=models.ImageField(blank=True, null=True, upload_to='article/imag'),
        ),
        migrations.AddField(
            model_name='article',
            name='image_body_13',
            field=models.ImageField(blank=True, null=True, upload_to='article/imag'),
        ),
        migrations.AddField(
            model_name='article',
            name='image_body_14',
            field=models.ImageField(blank=True, null=True, upload_to='article/imag'),
        ),
        migrations.AddField(
            model_name='article',
            name='image_body_9',
            field=models.ImageField(blank=True, null=True, upload_to='article/imag'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_11',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='title_12',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='title_13',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='title_14',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='title_9',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 9, 9, 10, 17, 24, 292007, tzinfo=utc)),
        ),
    ]
